version: '3.3'

services:
  oracle_service:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle_container
    networks:
      - backend
    ports:
      - "1521:1521"
      - "8081:8080"
    restart: unless-stopped
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    volumes:
      - oracle_data:/ORCL
volumes:
  oracle_data:
networks:
  backend: